### PR TITLE
Fix mount loop processing to avoid crash on invalid path

### LINKED ISSUE #120: Random mount failure when using docker in docker
Hi

I am using docker in docker (through sharing the docker.sockl file) to create container in a CI container.
Building a rockerfile within the container randomly fails with a "can't make ... relative to ..." error.

I've found that the issue is coming from the src/dockerclient/matrix.go file in the function ResolveHostPath. The mount array order is not guarantee and an invalid mount (with [] in its name) is processed by the loop. This triggers an error and fails the build.

I am going to issue a PR to solve this.

Regards

### PR DESCRIPTION
**Pull request by aacebedo**
Instead of leaving the loop when an invalid path is encountered, I ignore it and pass to the next one.

### CODE REVIEW

File: src/dockerclient/matrix.go [hunk 1]
```diff
@@ -75,10 +75,11 @@ func ResolveHostPath(mountPath string, client *docker.Client, isUnixSocket bool,
 	}
 
 	// Check if the given path is inside some mounted volumes
-	for _, mount := range container.Mounts {
+MountLoop:
+    for _, mount := range container.Mounts {
 		rel, err := filepath.Rel(mount.Destination, mountPath)
 		if err != nil {
-			return "", err
+			continue MountLoop
```
Comment (ybogdanov) [inline src/dockerclient/matrix.go]: Wait. Why not just `continue`?

**Comment by aacebedo** [comment]
Documentation of golang describes the continue like this. However it shall be possible to use it without the label. If you prefer this I can rework the commit and retest it

**Comment by aacebedo** [comment]
Re-read the doc and other example. Continue without label shall definitely do the job. I am going to edit the commit and repush it

**Comment by aacebedo** [comment]
done pushed the modification
